# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPlace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('product_tag', models.CharField(max_length=100)),
                ('product_attribute', models.CharField(max_length=100)),
                ('product_value', models.CharField(max_length=100)),
                ('image_tag', models.CharField(max_length=100)),
                ('image_attribute', models.CharField(max_length=100)),
                ('image_value', models.CharField(max_length=100)),
                ('link_tag', models.CharField(max_length=100)),
                ('link_attribute', models.CharField(max_length=100)),
                ('link_value', models.CharField(max_length=100)),
                ('price_tag', models.CharField(max_length=100)),
                ('price_attribute', models.CharField(max_length=100)),
                ('price_value', models.CharField(max_length=100)),
                ('name_tag', models.CharField(max_length=100)),
                ('name_attribute', models.CharField(max_length=100)),
                ('name_value', models.CharField(max_length=100)),
            ],
        ),
    ]
