# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchplace',
            name='price_decimal',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchplace',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='searchplace',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
