# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180220_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchplace',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
