# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180225_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchplace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
