# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180323_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchplace',
            name='vendor_logo',
            field=models.CharField(default='https://s0emagst.akamaized.net/layout/ro/images/logo//38/57629.png', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
