# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_json',
            field=models.BooleanField(default=False),
        ),
    ]
