# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_courier_is_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierParams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_label', models.CharField(max_length=100)),
                ('param_value', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='courier',
            name='result_attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='result_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courierparams',
            name='courier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Courier'),
        ),
        migrations.AlterUniqueTogether(
            name='courierparams',
            unique_together=set([('courier_id', 'param_label')]),
        ),
    ]
