# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20180511_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierparams',
            name='param_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
