# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 20:00
from __future__ import unicode_literals

from django.db import migrations
from search.models import CourierParams, Courier

def add_couriers():
    fan = Courier.objects.create(url="https://www.fancourier.ro/wp-content/themes/fancourier/webservice.php",
                           result_tag="3",
                           result_attribute="mstex",
                           result_value="",
                           is_json=True)

    cargus = Courier.objects.create(url="https://app.urgentcargus.ro/Private/Tracking.aspx",
                           result_tag="div",
                           result_attribute="class",
                           result_value="awb_track",
                           is_json=False)
    return fan, cargus

def add_params(apps, schema_editor):
    fan, cargus = add_couriers()
    cargus_dict = {"__ASYNCPOST":	"true",
                "__EVENTARGUMENT": "",
                "__EVENTTARGET": "",
                "__EVENTVALIDATION": "/q3VDS407vyeHJ4+ZnX9LnBeYjgFoPdn817j0NPuiylyDTjy76wMd8a7kykGtsBouvp8ylcE8w99jb5ZkBqVtDVJeU6l5GW60ohIha476Su52TUspOesLAbTSs8D199jzRqE4/TkwV1nFWqw83Id+PVhiQ1o3q9ZqVDSVBPOLHrISXwFePHqPfhZfiUyWwoFWpZgugKbjOgZcAEi2mZ7n4jmTyPXdZ0Ez9F8jlH/68Vk2oVYrDLHJcz3ve3GrCwFefYxt1KJ88gJqj1srdSnEELZF74=",
                "__LASTFOCUS": "",
                "__VIEWSTATE":	"iz87hjtpz3iHAJ6pa1n117VAFUtj1caHxxstNMkEkMF1cX/Kd5h7vX0yGEM2OX4FRgIFf9T6ITsYBzJiiZOfvbDqUqytYiEdjDWwqmMTx3Ks74xxqKEqwbL6fKk5RWJ6VXZO2CBuBVY85EBtq74pdUfEsq/oMJUtZ18hWUgy8Uu8gk1v4Ht8q98kaV29hcPa8ZujWk320POSd/HgEl8xAC2GSLNFGdoyZ9qcwnEhgu17dDDOtH33YfQ5ZfI1LdVbREEYgCdIn9zN2fD8Io+7mtdhkbCsquB+CuMxAVCGrvg8qC5jj1D9e6LH9PSXRkE2nBm6Bysp0v8eQxBrGr459k/YF4T22Wix8NVL25jQVv0sAZlaMzk5HfCTWZqfm0Hd02QNd5ydod6rm9rVrFnkNvXpNxvFxQRc+yzA6aF724RIvtylUBrfshaPGMwlxozionMwpjy3VSY5HNlSsXZ096cTRUEG6lZbmcVciMYsit/vW7sk2I63/j07gQ99ilU1…sBuUSXdnYEZmuM2Sg2hiR0iIFoxMROkeSwwbGTUW0y8w/MtAN3vBfIgTGelz1mGj3IQVkCFZRFCJsxyTGGIG5PrinbhBP6qPm6r1SJDtqi/MDUe11Ydlol8cyzQN46O+UWn0v2sCDkyes6idj8fK9pVMTQx7zzTKGgqtw+kb2DHJqe23UuD0dF/NqdyagvB19eRLEc/gIKF7Z0NnncMcA0aCyiDaZb5dh6+BF/ajJQvNeFgO5+H3QEbzwo6CYb8bFiHeN28nUN+F4WYvnUo8DCFXJf7sQU6mSSHpTOtucmcMfTzR7Zl/rMYF5Pnv3Ji2U0LT57rYuoZK6rA2tdAJ8BuMXFyYJ9XmjTXOVxvcQgWedp+Ff1fNSXgiQ45hLk6HpBKI+VlqyL9sIVJdHr0hm2evo1ca+hpbBLhHSOajEzTHwaGvM6jUNkGi6/xK4KVQxcbzNbV0AA/iLU5Czm6H2m7lK1nMAGyqbLRZAB8knkY4No+ebcP03YoRzhHEo0=",
                "__VIEWSTATEGENERATOR": "3CCCFCFF",
                "ctl00$Password": "",
                "ctl00$PrivateMainContent$awb_tracking": "Afiseaza AWB",
                "ctl00$PrivateMainContent$serie_awb": "123",
                "ctl00$ScriptManager": "ctl00$PrivateMainContent$pnl_box_tracking|ctl00$PrivateMainContent$awb_tracking",
                "ctl00$UserName": ""}

    fan_dict = {"awb": "123",
                "bar_size": "x",
                "bill": "",
                "limba": "romana",
                "metoda": "tracking"}
    for label in cargus_dict:
        CourierParams.objects.create(courier_id=cargus,
                                  param_label=label,
                                  param_value=cargus_dict.get('label'))

    for label in fan_dict:
        CourierParams.objects.create(courier_id=fan,
                                     param_label=label,
                                     param_value=fan_dict.get('label'))


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20180511_2023'),
    ]

    operations = [
        migrations.RunPython(add_params)
    ]
