# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 17:32
from __future__ import unicode_literals

from django.db import migrations
from search.models import SearchPlace


emag = {
    "name": "EMAG",
    "url": "https://www.emag.ro/search/",
    "vendor_logo": "https://s0emagst.akamaized.net/layout/ro/images/logo//38/57629.png",
    "product_tag": "div",
    "product_attribute": "class",
    "product_value": "card",
    "image_tag": "div",
    "image_attribute": "class",
    "image_value": "thumbnail",
    "link_tag": "a",
    "link_attribute": "class",
    "link_value": "thumbnail-wrapper js-product-url",
    "price_tag": "p",
    "price_attribute": "class",
    "price_value": "product-new-price",
    "price_decimal": "2",
    "name_tag": "a",
    "name_attribute": "class",
    "name_value": "product-title js-product-url",
    "category_tag": "1",
    "category_attribute": "1",
    "category_value": "1",
}


pcgarage = {
    "name": "PCGarage",
    "url": "https://www.pcgarage.ro/cauta/",
    "vendor_logo": "/staticfiles/logo-pcgarage.jpg",
    "product_tag": "div",
    "product_attribute": "class",
    "product_value": "product-box",
    "image_tag": "div",
    "image_attribute": "class",
    "image_value": "pb-image",
    "price_tag": "div",
    "price_attribute": "class",
    "price_value": "pb-price",
    "price_decimal": "2",
    "name_tag": "div",
    "name_attribute": "class",
    "name_value": "pb-name",
    "category_tag": "a",
    "category_attribute": "class",
    "category_value": "cat-nav-tab",
}


def add_data(apps, schema_editor):
    SearchPlace.objects.create(**emag)
    SearchPlace.objects.create(**pcgarage)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20180511_2023'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
