# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20180517_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierparams',
            name='param_value',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
