# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 17:58
from __future__ import unicode_literals

from django.db import migrations
from search.models import Courier, CourierParams

fan_courier = {
    "url": "https://www.fancourier.ro/wp-content/themes/fancourier/webservice.php",
    "result_tag": "3",
    "result_attribute": "mstex",
    "result_value": "",
    "is_json": "1"
}


cargus = {
    "url": "https://app.urgentcargus.ro/Private/Tracking.aspx",
    "result_tag": "div",
    "result_attribute": "class",
    "result_value": "awb_track",
    "is_json": "0"
}


def courier_params(fan_courier, cargus):
    courier_params_object=[{
            "param_label": "ctl00$UserName",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "__ASYNCPOST",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "__LASTFOCUS",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "__EVENTTARGET",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "__EVENTARGUMENT",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "__VIEWSTATE",
            "param_value": "kfppm04IC63xmp2F2kjKmOr4xUqTvxkknD0P+TD+DAEmuf52E7YzYHTqJSJpmZtGfxD0wMSgYy/As5CziaabEqbGVq7Kay1UpvsdAQfoxvZMLt8EUQorNcljn+WxoUZbkGtdiaXj7CmSZy0lklBkzPp2Mv2Mt5SWy50qBUALlq5GUvaOrfGl94JliQNdYv00NRWiA0z/vd5jYRKe9jDStWJYio2txCb2CEePWVzjXNJxdy3W8VgZyiMO5chd/dhYhShX6GI0vtglZRgd2Tf+OEU9CersP7TJXJKQ3+CAKaqQ9va5awSdGgu8nkHX7WsmcjFb6L5RpDBQvzjDDuNfpcqYg0rPxLbn+mPYPDJDbDpJF27Dkns/Wq/iuOIlTWozUmZduKGomN6UIoxjyldzVIMzkdYhROJUD7ln215KIgYuewrw/IX3NoNUFG2svqH8+HJwH07NZBD77AMU4yTjmUQhqnzHW/PEhs2jOHBIdxc7flIHZPk1WUYSysOY3yGpAS9KLqXyxkj53am7YymohS9MVudwJ5w1kUdp+OItxh1BAASRCA7NFRFAorBiBitoP/IBc7Fu8XbGu/gs6YQDCwM0wUtdd+uJ+9FMJeO6/nwH2RONCSVv8p7s2iAYiTLSL1eY+Wjkphv5BsmfX8XKeM4WcKtMOXM+WToGqJclBSeGdhWzqDOZX3l5Rq9LWv4HZ7U6I3PHsrBMjUk2oerNHuzA4mKN7rJqxgItsb+i7/nrBQxfageAov6iCIGMlgkGnHsp9eE4MoARLeKUGL1SK6+mWQB7U8K7u1eFoXxuv+HpM2ap9/X+i8gg2pps2tF2i8Pjf4Dri3tHwR2csQosBHqv77266YsA/xydfpPSjQWWF8cN/Ug+v1je3dK3auNWiUdYuN2bvcmh9QFrqaVjPISD7np3LYOe/4hPcUYbgIPJ/kvKMPlL06I2bPpdJzmGavjtlp5XISjMfzJlluEzof+1EIB1QtBJe2C7VnElfkzoomfcomr3C7+KBuVPnhOx/SzL3Wp7/yAkNnZgU/dQEwgNhNIZFmBjkF+qd6/h597Kv8SVAX/TF/lXNVuTnVdJD77JdjXF/5dPMA+xroIK4aRS9+ONlnEM3qPyKwq5Hg13z+JSpTOdU/0fIYyg0fCYI8y9e7pt3s4bg5OmISYbYbDZboEPvOdGW428eT73gWNxr/D+a8ELOQN5WQIPppKXCehciRJT7JehxvuObItBLgEvZ/UXZ/83P8CuO/jwFZMMaKFPoEpiU8TDVCtB5t5Utxv6ogagsGfsgUGLAE7+j9X7aiQzf0nFRfI8FbM6PskSTD9rpilDYXWC46xkZRe+hRZyFNYml3Fs7wYFau/+q3eQAKw7g4L9rgAVOn53bJ0lSr4jXoaumhRqEVzNgZT+zNlHhw==",
            "courier_id": cargus
        },
        {
            "param_label": "__VIEWSTATEGENERATOR",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "__EVENTVALIDATION",
            "param_value": "rPN+4y/14UhE7IgfjK4jS+PsZ1PJjZx88VQVLc+5+hj8ZR7lKzOlu/3efba2RxS/8aIP5QoMaoeRjdoH58R99eoNeGDZqZHK+vHaxK3xrDIgqGCcTsUuTz/hQfnrtqd6WfN3GwUNh32NM6OpF4ItndDdXQppkV0TVDvDmkU3QcbiLTYCvXAkaDkeMoWI5ncT7bj1X/3FL5ETDmcrfedvqZBEolsmZHXhAKAt3QjDMsm+UYsr3ddbchd+Lk5d9jsLaVLFQw==",
            "courier_id": cargus
        },
        {
            "param_label": "ctl00$Password",
            "param_value": None,
            "courier_id": cargus
        },
        {
            "param_label": "ctl00$PrivateMainContent$serie_awb",
            "param_value": "awb",
            "courier_id": cargus
        },
        {
            "param_label": "ctl00$PrivateMainContent$awb_tracking",
            "param_value": "Afiseaza AWB",
            "courier_id": cargus
        },
        {
            "param_label": "awb",
            "param_value": "awb",
            "courier_id": fan_courier
        },
        {
            "param_label": "bill",
            "param_value": None,
            "courier_id": fan_courier
        },
        {
            "param_label": "metoda",
            "param_value": "tracking",
            "courier_id": fan_courier
        },
        {
            "param_label": "limba",
            "param_value": "romana",
            "courier_id": fan_courier
        }
    ]
    for param in courier_params_object:
        CourierParams.objects.create(**param)


def add_data(apps, schema_editor):
    import ipdb; ipdb.set_trace()
    Courier.objects.create(**cargus)
    cargus_object = Courier.objects.get(url=cargus.get('url'))
    Courier.objects.create(**fan_courier)
    fan_courier_object = Courier.objects.get(url=fan_courier.get('url'))
    courier_params(fan_courier_object, cargus_object)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20180524_1447'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
